- name: Install IIS and create site 
  hosts: win 
  tasks:
    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present
    - name: Create Folder for site
      win_file:
        path: C:\inetpub\wwwroot\HelloWorld
        state: directory
    - name: Create IIS site
      win_iis_website:
        name: HelloWorld
        state: started
        physical_path: C:\inetpub\wwwroot\HelloWorld
    - name: Create HTML page for site
      win_file:
        path: C:\inetpub\wwwroot\HelloWorld\index.html
        state: touch
    - name: Add content to HTML page
      win_file:
        path: C:\inetpub\wwwroot\HelloWorld\index.html
        content: "Hello World"
    - name: Add a HTTPS binding
      community.windows.win_iis_webbinding:
        name: HelloWorld
        certificate_store_name: "/home/Ansible/"
        protocol: https
        port: 443
        ip: 3.127.223.33
        state: present
    - name: Install DNS
      win_feature:
        name: DNS
        state: present
    - name: Create domain
      win_domain:
        dns_domain_name: dors.domain
        safe_mode_password: notSecure
    - name: Restart an application pool (non-idempotent)
      community.windows.win_iis_webapppool:
        name: HelloWorld
        state: restarted
    - name: Push a new Index.html config file
      template:
        src: index.j2
        dest: C:\inetpub\wwwroot\HelloWorld\index2.html
        mode: 0775
