---
- name: Install IIS
  hosts: all
  gather_facts: true
  tasks:
   - name: Install IIS
     win_feature:
       name: "Web-Server"
       state: present
       include_sub_features: yes
       include_management_tools: yes
   - name: Copy index text page
     win_copy:
       src: "Index.html"
       dest: "C:\\inetpub\\wwwroot\\ansible.html"
   - name: Add a HTTPS binding
     community.windows.win_iis_webbinding:
       name: Default Web Site
       protocol: https
       port: 443
       ssl certificate: SelfSigned
       state: present
